"""
Task definitions for the Multi-Agent Software Development System
"""
from crewai import Task
from config import Config

class TaskFactory:
    """Factory class for creating tasks"""
    
    @staticmethod
    def create_development_task(agent, requirements: str, project_name: str = "project") -> Task:
        """Create a development task"""
        config = Config.TASK_CONFIGS["development"]
        
        return Task(
            description=f"""
            {config['description']}
            
            Requirements:
            {requirements}
            
            Project: {project_name}
            
            CRITICAL: You MUST generate actual working code files, not just documentation.
            
            Please:
            1. Analyze the requirements thoroughly
            2. Design a proper architecture
            3. Write clean, well-documented code
            4. Include proper error handling
            5. Add comprehensive comments
            6. Follow best practices for the chosen technology stack
            7. Create a README.md with setup and usage instructions
            
            IMPORTANT OUTPUT REQUIREMENTS:
            - Generate the main code file (e.g., main.py, app.py, index.js, etc.)
            - Include all necessary imports and dependencies
            - Make the code immediately runnable
            - Provide clear usage examples
            - Include proper error handling and validation
            
            Your response should include:
            1. The main code file with complete implementation
            2. Any additional files needed (requirements.txt, config files, etc.)
            3. A comprehensive README.md with setup instructions
            4. Usage examples and documentation
            
            Format your response with proper code blocks:
            ```python
            # Your Python code here
            ```
            
            ```markdown
            # Your README content here
            ```
            
            Make sure the code is complete and can be run immediately!
            """,
            agent=agent,
            expected_output="Complete, working code files with proper structure, error handling, and documentation"
        )
    
    @staticmethod
    def create_review_task(agent, project_name: str = "project") -> Task:
        """Create a code review task"""
        config = Config.TASK_CONFIGS["review"]
        
        return Task(
            description=f"""
            {config['description']}
            
            Project: {project_name}
            
            Please review the code generated by the Software Developer Agent and provide:
            1. Code quality assessment
            2. Security vulnerability analysis
            3. Performance considerations
            4. Best practices compliance
            5. Specific improvement suggestions
            6. Architecture review
            7. Documentation quality check
            8. Testing recommendations
            
            Be thorough and constructive in your feedback.
            Focus on the actual code implementation, not just documentation.
            """,
            agent=agent,
            expected_output="Detailed code review with specific suggestions and improvements"
        ) 